/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trackedu;

/**
 *
 * @author divya
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
public class TimetableEditorA extends javax.swing.JFrame {
    private JTable table;
    private DefaultTableModel model;
    private Connection conn;
    /**
     * Creates new form TimetableEditorA
     */
    public TimetableEditorA() {
         setTitle("Timetable Editor");
        setSize(817, 477);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Initialize Database Connection
        connectToDatabase();

        // Column headers
        String[] columns = {"Time Slot", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"};
        
        // Retrieve data from the database
        model = new DefaultTableModel(columns, 0);
        loadTimetableData();

        // Initialize table with model
        table = new JTable(model);
        table.setFillsViewportHeight(true);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        // Save button
        JButton saveButton = new JButton("Save Changes");
        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveTimetableData();
            }
        });
        add(saveButton, BorderLayout.SOUTH);
    }

    // Connect to the database
    private void connectToDatabase() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/college", "root", "admin");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database connection failed.");
        }
    }

    // Load timetable data from the database into JTable
    private void loadTimetableData() {
        try (Statement stmt = conn.createStatement()) {
            ResultSet rs = stmt.executeQuery("SELECT * FROM timetableA");
            while (rs.next()) {
                String[] row = {
                    rs.getString("time_slot"),
                    rs.getString("monday"),
                    rs.getString("tuesday"),
                    rs.getString("wednesday"),
                    rs.getString("thursday"),
                    rs.getString("friday")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Save updated data back to the database
    private void saveTimetableData() {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE timetableA SET monday = ?, tuesday = ?, wednesday = ?, thursday = ?, friday = ? WHERE time_slot = ?")) {
            for (int row = 0; row < model.getRowCount(); row++) {
                ps.setString(1, (String) model.getValueAt(row, 1));
                ps.setString(2, (String) model.getValueAt(row, 2));
                ps.setString(3, (String) model.getValueAt(row, 3));
                ps.setString(4, (String) model.getValueAt(row, 4));
                ps.setString(5, (String) model.getValueAt(row, 5));
                ps.setString(6, (String) model.getValueAt(row, 0));
                ps.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Changes saved to database.");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new TimetableEditorA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
